# NumPy

In [1]:
import numpy as np

## 1. Array Creation

### 1-1. List to Array

In [2]:
list_1 = [1,2,3,4]
list_2 = ['a','b','c','d','e']
list_3 = [[1,2,3],[4,5,6],[7,8,9]]
print(list_1)
print(list_2)
print(list_3)

[1, 2, 3, 4]
['a', 'b', 'c', 'd', 'e']
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [3]:
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = np.array(list_3)
print(array_1)
print(array_2)
print(array_3)

[1 2 3 4]
['a' 'b' 'c' 'd' 'e']
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 1-2. Arange

In [4]:
range_list = list(range(5))
range_array = np.arange(5)
print(range_list)
print(range_array)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [5]:
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


### 1-3. Linspace

In [6]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [7]:
np.linspace(0,100,60)

array([  0.        ,   1.69491525,   3.38983051,   5.08474576,
         6.77966102,   8.47457627,  10.16949153,  11.86440678,
        13.55932203,  15.25423729,  16.94915254,  18.6440678 ,
        20.33898305,  22.03389831,  23.72881356,  25.42372881,
        27.11864407,  28.81355932,  30.50847458,  32.20338983,
        33.89830508,  35.59322034,  37.28813559,  38.98305085,
        40.6779661 ,  42.37288136,  44.06779661,  45.76271186,
        47.45762712,  49.15254237,  50.84745763,  52.54237288,
        54.23728814,  55.93220339,  57.62711864,  59.3220339 ,
        61.01694915,  62.71186441,  64.40677966,  66.10169492,
        67.79661017,  69.49152542,  71.18644068,  72.88135593,
        74.57627119,  76.27118644,  77.96610169,  79.66101695,
        81.3559322 ,  83.05084746,  84.74576271,  86.44067797,
        88.13559322,  89.83050847,  91.52542373,  93.22033898,
        94.91525424,  96.61016949,  98.30508475, 100.        ])

### 1-4. Ones, Zeros, Eye

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 1-5. Random

In [13]:
np.random.rand(5)

array([0.45800935, 0.83926472, 0.47532181, 0.9303635 , 0.58662059])

In [14]:
np.random.rand(3,3)

array([[0.52301827, 0.8828878 , 0.99214644],
       [0.84418452, 0.4716609 , 0.58543114],
       [0.31319717, 0.8909534 , 0.87894021]])

In [15]:
np.random.randint(1,10,5)

array([9, 8, 2, 3, 9])

In [16]:
norm_d = np.random.randn(100)
norm_d.sort()
print(norm_d)

[-2.94406414 -2.25607776 -2.00166303 -1.95645423 -1.78824012 -1.61294877
 -1.59255422 -1.57578138 -1.52306653 -1.50244722 -1.44359933 -1.42857676
 -1.28927997 -1.25700943 -1.18859457 -1.16276313 -1.12048361 -1.0947813
 -0.96203172 -0.86390215 -0.85278207 -0.85070984 -0.73603163 -0.72840845
 -0.6743499  -0.65005073 -0.57160635 -0.56186596 -0.52170052 -0.48226839
 -0.48224809 -0.43076169 -0.41981637 -0.4093813  -0.40309376 -0.39776252
 -0.37142244 -0.34787299 -0.33753006 -0.32678997 -0.31831648 -0.30711476
 -0.30604243 -0.2943758  -0.19761235 -0.1800431  -0.17264433 -0.1214456
 -0.0803513  -0.00567986  0.00509317  0.09225972  0.1207102   0.16663823
  0.2132423   0.22630892  0.2608579   0.26091348  0.26192718  0.32879327
  0.33987848  0.35233428  0.36990134  0.39427753  0.3983041   0.43036015
  0.45268791  0.4614858   0.49572381  0.49614684  0.52205361  0.54913976
  0.5542658   0.56259505  0.59558145  0.69162508  0.75924904  0.76876276
  0.90791398  0.935291    0.9550087   1.01765397  1.0

### 1-6. min, max, sum, mean, argmin, argmax

In [17]:
sample_matrix = np.random.randint(1,10,5)
print(sample_matrix)

[9 4 5 9 4]


In [18]:
sample_matrix.max()

9

In [19]:
sample_matrix.min()

4

In [20]:
sample_matrix.sum()

31

In [21]:
sample_matrix.mean()

6.2

In [22]:
sample_matrix.argmin()

1

In [23]:
sample_matrix.argmax()

0

### 1-7. Shape, Reshape

In [24]:
sample_matrix = np.random.randint(1,10,9)
print(sample_matrix)
print(sample_matrix.shape)

[8 7 4 7 8 6 9 7 4]
(9,)


In [25]:
sample_matrix = sample_matrix.reshape(3,3)
print(sample_matrix)

[[8 7 4]
 [7 8 6]
 [9 7 4]]


In [26]:
sample_matrix.shape

(3, 3)

## 2. Array Selection


### 2-1. Basic Selction

In [27]:
sample_array = np.random.randint(1,10,9)
print(sample_array)

[1 7 8 5 4 5 8 6 4]


In [28]:
sample_array[3]

5

In [29]:
sample_array[-1]

4

In [30]:
sample_array[1:3]

array([7, 8])

In [31]:
sample_array[1:]

array([7, 8, 5, 4, 5, 8, 6, 4])

In [32]:
sample_array[:-3]

array([1, 7, 8, 5, 4, 5])

In [33]:
sample_array[-3:]

array([8, 6, 4])

### 2-2. Assigning value

In [34]:
sample_array = np.random.randint(1,10,9)

In [35]:
sample_array[0:5] = -50
print(sample_array)

[-50 -50 -50 -50 -50   6   4   9   6]


In [36]:
sample_array[:] = 100
print(sample_array)

[100 100 100 100 100 100 100 100 100]


In [37]:
sample_array[:] += 100
print(sample_array)

[200 200 200 200 200 200 200 200 200]


In [38]:
sample_array[:] *= 3
print(sample_array)

[600 600 600 600 600 600 600 600 600]


### 2-3. N-dimensional selection

In [39]:
sample_matrix = np.random.randint(1,10,16).reshape(4,4)
print(sample_matrix)

[[2 7 3 6]
 [4 7 1 4]
 [2 6 9 2]
 [3 1 4 1]]


In [40]:
sample_matrix[0]

array([2, 7, 3, 6])

In [41]:
sample_matrix[-1]

array([3, 1, 4, 1])

In [42]:
sample_matrix[0:3]

array([[2, 7, 3, 6],
       [4, 7, 1, 4],
       [2, 6, 9, 2]])

In [43]:
sample_matrix[0][1]

7

In [44]:
sample_matrix[0,1]

7

In [45]:
sample_matrix[:,0]

array([2, 4, 2, 3])

In [46]:
sample_matrix[:,:1]

array([[2],
       [4],
       [2],
       [3]])

In [47]:
sample_matrix[:2,2:]

array([[3, 6],
       [1, 4]])

In [48]:
sample_matrix[[1,3]]

array([[4, 7, 1, 4],
       [3, 1, 4, 1]])

### 2-4. Conditional selction

In [49]:
[sample_matrix>5]

[array([[False,  True, False,  True],
        [False,  True, False, False],
        [False,  True,  True, False],
        [False, False, False, False]])]

In [50]:
sample_matrix[sample_matrix>5]

array([7, 6, 7, 6, 9])

## 3. Array Operation


In [51]:
m = np.arange(1,10).reshape((3,3))
a = np.ones((3,3))
print(m)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3-1. Basic operation

In [52]:
m+a

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [53]:
m-a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [54]:
m*a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [55]:
np.dot(m,a)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [56]:
a/m

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

### 3-2. Advanced operations

More useful functions can be found [here](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [57]:
m = np.arange(1,10).reshape((3,3))*-1
a = np.ones((3,3)) * 2
print(m)
print(a)

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [58]:
m = np.fabs(m)
print(m)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [59]:
np.log(m)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [60]:
np.exp(m)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [61]:
np.sin(m)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [62]:
np.lcm(m.astype(int),3)

array([[ 3,  6,  3],
       [12, 15,  6],
       [21, 24,  9]])

In [63]:
np.gcd(m.astype(int),3)

array([[1, 1, 3],
       [1, 1, 3],
       [1, 1, 3]])

In [64]:
np.greater(m,a)

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])